# General Settings
baseURL = 'https://themindfulmettle.com/'
languageCode = 'en-us'
title = 'The Mindful Mettle'
theme = 'luique'
resourceDir = "resources"
paginate = 6
summaryLength = 20
DefaultContentLanguage = "en"

# Menu Settings
[menu]



# Main Settings
[params]
defaultSkin = "light"  # select default UI: "light" or "dark"
dateFormat = "March 15, 2023"
authorName = "The Mindful Mettle"
disqusComments = "test" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "" #YOUR FORMSPREE URL
googleAnalytics = "" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[params.preloader]
logo = "images/logo2.png"
alt = "The Mindful Mettle"

# Header Settings
[params.header]
logo = "images/logo2.png"
logo_alt =  "The Mindful Mettle"

# Footer Settings
[params.footer]
copyright = "© 2023 <strong></strong>. All rights reserved"
developer = "Developed by <strong>The Mindful Mettal Team</strong>"

# Social Settings
[[params.social]]
title = "Twitter"
icon = "fab fa-twitter"
url = "https://www.twitter.com/"
weight = 1
[[params.social]]
title = "Dribbble"
icon = "fab fa-dribbble"
url = "https://www.dribbble.com/"
weight = 2
[[params.social]]
title = "Behance"
icon = "fab fa-behance"
url = "https://www.behance.net/"
weight = 3

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
layout = "list" # select works layout options: "grid" or "list"
[[params.portfolio.filters]]
name = "UI UX Design"
slug = "ui-ux-design"
[[params.portfolio.filters]]
name = "Photography"
slug = "photography"
[[params.portfolio.filters]]
name = "Development"
slug = "development"
[[params.portfolio.filters]]
name = "Branding"
slug = "branding"

# Sidebar
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

# Sitemap Settings
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true